/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/nameof/sample-controller/pkg/apis/nameof.github.com/v1"
	nameofgithubcomv1 "github.com/nameof/sample-controller/pkg/client/applyconfiguration/nameof.github.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGithubInfos implements GithubInfoInterface
type FakeGithubInfos struct {
	Fake *FakeNameofV1
	ns   string
}

var githubinfosResource = v1.SchemeGroupVersion.WithResource("githubinfos")

var githubinfosKind = v1.SchemeGroupVersion.WithKind("GithubInfo")

// Get takes name of the githubInfo, and returns the corresponding githubInfo object, and an error if there is any.
func (c *FakeGithubInfos) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.GithubInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(githubinfosResource, c.ns, name), &v1.GithubInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GithubInfo), err
}

// List takes label and field selectors, and returns the list of GithubInfos that match those selectors.
func (c *FakeGithubInfos) List(ctx context.Context, opts metav1.ListOptions) (result *v1.GithubInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(githubinfosResource, githubinfosKind, c.ns, opts), &v1.GithubInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.GithubInfoList{ListMeta: obj.(*v1.GithubInfoList).ListMeta}
	for _, item := range obj.(*v1.GithubInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested githubInfos.
func (c *FakeGithubInfos) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(githubinfosResource, c.ns, opts))

}

// Create takes the representation of a githubInfo and creates it.  Returns the server's representation of the githubInfo, and an error, if there is any.
func (c *FakeGithubInfos) Create(ctx context.Context, githubInfo *v1.GithubInfo, opts metav1.CreateOptions) (result *v1.GithubInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(githubinfosResource, c.ns, githubInfo), &v1.GithubInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GithubInfo), err
}

// Update takes the representation of a githubInfo and updates it. Returns the server's representation of the githubInfo, and an error, if there is any.
func (c *FakeGithubInfos) Update(ctx context.Context, githubInfo *v1.GithubInfo, opts metav1.UpdateOptions) (result *v1.GithubInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(githubinfosResource, c.ns, githubInfo), &v1.GithubInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GithubInfo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGithubInfos) UpdateStatus(ctx context.Context, githubInfo *v1.GithubInfo, opts metav1.UpdateOptions) (*v1.GithubInfo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(githubinfosResource, "status", c.ns, githubInfo), &v1.GithubInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GithubInfo), err
}

// Delete takes name of the githubInfo and deletes it. Returns an error if one occurs.
func (c *FakeGithubInfos) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(githubinfosResource, c.ns, name, opts), &v1.GithubInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGithubInfos) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(githubinfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.GithubInfoList{})
	return err
}

// Patch applies the patch and returns the patched githubInfo.
func (c *FakeGithubInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GithubInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(githubinfosResource, c.ns, name, pt, data, subresources...), &v1.GithubInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GithubInfo), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied githubInfo.
func (c *FakeGithubInfos) Apply(ctx context.Context, githubInfo *nameofgithubcomv1.GithubInfoApplyConfiguration, opts metav1.ApplyOptions) (result *v1.GithubInfo, err error) {
	if githubInfo == nil {
		return nil, fmt.Errorf("githubInfo provided to Apply must not be nil")
	}
	data, err := json.Marshal(githubInfo)
	if err != nil {
		return nil, err
	}
	name := githubInfo.Name
	if name == nil {
		return nil, fmt.Errorf("githubInfo.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(githubinfosResource, c.ns, *name, types.ApplyPatchType, data), &v1.GithubInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GithubInfo), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeGithubInfos) ApplyStatus(ctx context.Context, githubInfo *nameofgithubcomv1.GithubInfoApplyConfiguration, opts metav1.ApplyOptions) (result *v1.GithubInfo, err error) {
	if githubInfo == nil {
		return nil, fmt.Errorf("githubInfo provided to Apply must not be nil")
	}
	data, err := json.Marshal(githubInfo)
	if err != nil {
		return nil, err
	}
	name := githubInfo.Name
	if name == nil {
		return nil, fmt.Errorf("githubInfo.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(githubinfosResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.GithubInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GithubInfo), err
}
