apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: githubinfos.nameof.github.com
spec:
  group: nameof.github.com
  names:
    kind: GithubInfo
    listKind: GithubInfoList
    plural: githubinfos
    singular: githubinfos
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                link:
                  type: string
                repoCount:
                  format: int32
                  type: integer
              required:
                - username
                - link
                - repoCount
      additionalPrinterColumns:
        - name: Github-Username
          type: string
          jsonPath: .spec.username
